name: Ruby Gem

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Cache CocoaPods
      uses: actions/cache@v3
      with:
        key: ${{ hashFiles('Podfile.lock') }}
        path:
          "Pods"
        
    - name: Install pods
      run: bundle exec pod update
      
    - name: Create xcframeworks
      run: sh ./create-xcframeworks.sh
